In [3]:
import numpy as np

In [6]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr1.shape

(4,)

In [15]:
arr2.shape

(2, 3)

### Vectorized Math

In [45]:
nums = np.array([10, 20, 30, 40])

In [21]:
nums + 5

array([15, 25, 35, 45])

In [22]:
nums * 2

array([20, 40, 60, 80])

In [23]:
nums / 10

array([1., 2., 3., 4.])

In [24]:
nums ** 2

array([ 100,  400,  900, 1600])

### Basic Statistics

In [27]:
np.mean(nums)

np.float64(25.0)

In [28]:
np.std(nums)

np.float64(11.180339887498949)

In [29]:
np.min(nums)

np.int64(10)

In [30]:
np.max(nums)

np.int64(40)

### Indexing and Slicing

In [32]:
nums[0]

np.int64(10)

In [33]:
nums[-1]

np.int64(40)

In [34]:
nums[1:3]

array([20, 30])

### Reshaping

In [42]:
nums.reshape(2,2)

array([[10, 20],
       [30, 40]])

### Mini Project — NumPy Data Analysis

#### Task 1
##### Create a NumPy array representing 10 days of temperatures:

In [49]:
temps = np.array([70, 43, 89, 63, 45, 48, 28, 39, 50, 67])
temps

array([70, 43, 89, 63, 45, 48, 28, 39, 50, 67])

#### Task 2
##### Compute Basic Statistics:

In [50]:
mean_temp = np.mean(temps)
std_temp = np.std(temps)
min_temp = np.min(temps)
max_temp = np.max(temps)
mean_temp, std_temp, max_temp, min_temp

(np.float64(54.2), np.float64(16.987053894068858), np.int64(89), np.int64(28))

### Task 3
#### Using slicing, extract:
#### the first 3 days
#### the last 3 days
#### the middle 4 days (positions 3–6)

In [54]:
first_3_days = temps[0:3]
first_3_days

array([70, 43, 89])

In [58]:
last_3_days = temps[-3:]
last_3_days

array([39, 50, 67])

In [60]:
middle_4_days = temps[3:7]
middle_4_days

array([63, 45, 48, 28])

### Task 4
#### Normalize the temperatures in the dataset

In [61]:
normalized = (temps - np.min(temps)) / (np.max(temps) - np.min(temps))
normalized

array([0.68852459, 0.24590164, 1.        , 0.57377049, 0.27868852,
       0.32786885, 0.        , 0.18032787, 0.36065574, 0.63934426])

### Task 5
#### Reshape the data into a 2 row matrix

In [63]:
new_temps = temps.reshape(2,5)
new_temps

array([[70, 43, 89, 63, 45],
       [48, 28, 39, 50, 67]])